name: Cherry-pick PR commits to release branch

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  cherry-pick:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Get the PR commit hashes
      id: get-commits
      run: |
        COMMITS=$(git log --pretty=format:"%H" ${GITHUB_SHA}^1..${GITHUB_SHA})
        echo "::set-output name=commits::${COMMITS}"

    - name: Checkout the release branch
      run: git checkout release

    - name: Cherry-pick commits from the PR
      run: |
        for commit in ${{ steps.get-commits.outputs.commits }}
        do
          git cherry-pick $commit || git cherry-pick --abort
        done

    - name: Push changes to release branch
      run: git push origin prerelease/0.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}